function weaponimg(name){
  switch(name){
    case "AlleyHunter": return "/img/items/weapeon/all/AlleyHunter.png" 
    case "AmenomaKageuchi": return "/img/items/weapeon/all/AmenomaKageuchi.png" 
    case "AmosBow": return "/img/items/weapeon/all/AmosBow.png" 
    case "ApprenticeNotes": return "/img/items/weapeon/all/ApprenticeNotes.png" 
    case "AquilaFavonia": return "/img/items/weapeon/all/AquilaFavonia.png" 
    case "BeginnerProtector": return "/img/items/weapeon/all/BeginnerProtector.png" 
    case "BlackcliffAgate": return "/img/items/weapeon/all/BlackcliffAgate.png" 
    case "BlackcliffLongsword": return "/img/items/weapeon/all/BlackcliffLongsword.png" 
    case "BlackcliffPole": return "/img/items/weapeon/all/BlackcliffPole.png" 
    case "BlackcliffSlasher": return "/img/items/weapeon/all/BlackcliffSlasher.png" 
    case "BlackcliffWarbow": return "/img/items/weapeon/all/BlackcliffWarbow.png" 
    case "BlackTassel": return "/img/items/weapeon/all/BlackTassel.png" 
    case "BloodtaintedGreatsword": return "/img/items/weapeon/all/BloodtaintedGreatsword.png" 
    case "CompoundBow": return "/img/items/weapeon/all/CompoundBow.png" 
    case "CoolSteel": return "/img/items/weapeon/all/CoolSteel.png" 
    case "CrescentPike": return "/img/items/weapeon/all/CrescentPike.png" 
    case "DarkIronSword": return "/img/items/weapeon/all/DarkIronSword.png" 
    case "Deathmatch": return "/img/items/weapeon/all/Deathmatch.png" 
    case "DebateClub": return "/img/items/weapeon/all/DebateClub.png" 
    case "DodocoTales": return "/img/items/weapeon/all/DodocoTales.png" 
    case "DragonBane": return "/img/items/weapeon/all/DragonBane.png" 
    case "DragonspineSpear": return "/img/items/weapeon/all/DragonspineSpear.png" 
    case "DullBlade": return "/img/items/weapeon/all/DullBlade.png" 
    case "EbonyBow": return "/img/items/weapeon/all/EbonyBow.png" 
    case "ElegyfortheEnd": return "/img/items/weapeon/all/ElegyfortheEnd.png" 
    case "EmeraldOrb": return "/img/items/weapeon/all/EmeraldOrb.png" 
    case "EngulfingLightning": return "/img/items/weapeon/all/EngulfingLightning.png" 
    case "EverlastingMoonglow": return "/img/items/weapeon/all/EverlastingMoonglow.png" 
    case "EyeofPerception": return "/img/items/weapeon/all/EyeofPerception.png" 
    case "FavoniusCodex": return "/img/items/weapeon/all/FavoniusCodex.png" 
    case "FavoniusGreatsword": return "/img/items/weapeon/all/FavoniusGreatsword.png" 
    case "FavoniusLance": return "/img/items/weapeon/all/FavoniusLance.png" 
    case "FavoniusSword": return "/img/items/weapeon/all/FavoniusSword.png" 
    case "FavoniusWarbow": return "/img/items/weapeon/all/FavoniusWarbow.png" 
    case "FerrousShadow": return "/img/items/weapeon/all/FerrousShadow.png" 
    case "FesteringDesire": return "/img/items/weapeon/all/FesteringDesire.png" 
    case "FilletBlade": return "/img/items/weapeon/all/FilletBlade.png" 
    case "FreedomSworn": return "/img/items/weapeon/all/FreedomSworn.png" 
    case "Frostbearer": return "/img/items/weapeon/all/Frostbearer.png" 
    case "HakushinRing": return "/img/items/weapeon/all/HakushinRing.png" 
    case "Halberd": return "/img/items/weapeon/all/Halberd.png" 
    case "Hamayumi": return "/img/items/weapeon/all/Hamayumi.png" 
    case "HarbingerofDawn": return "/img/items/weapeon/all/HarbingerofDawn.png" 
    case "HunterBow": return "/img/items/weapeon/all/HunterBow.png" 
    case "IronPoint": return "/img/items/weapeon/all/IronPoint.png" 
    case "IronSting": return "/img/items/weapeon/all/IronSting.png" 
    case "KatsuragikiriNagamasa": return "/img/items/weapeon/all/KatsuragikiriNagamasa.png" 
    case "KitainCrossSpear": return "/img/items/weapeon/all/KitainCrossSpear.png" 
    case "LionRoar": return "/img/items/weapeon/all/LionRoar.png" 
    case "LithicBlade": return "/img/items/weapeon/all/LithicBlade.png" 
    case "LithicSpear": return "/img/items/weapeon/all/LithicSpear.png" 
    case "LostPrayertotheSacredWinds": return "/img/items/weapeon/all/LostPrayertotheSacredWinds.png" 
    case "LuxuriousSeaLord": return "/img/items/weapeon/all/LuxuriousSeaLord.png" 
    case "MagicGuide": return "/img/items/weapeon/all/MagicGuide.png" 
    case "MappaMare": return "/img/items/weapeon/all/MappaMare.png" 
    case "MemoryofDust": return "/img/items/weapeon/all/MemoryofDust.png" 
    case "Messenger": return "/img/items/weapeon/all/Messenger.png" 
    case "MistsplitterReforged": return "/img/items/weapeon/all/MistsplitterReforged.png" 
    case "MitternachtsWaltz": return "/img/items/weapeon/all/MitternachtsWaltz.png" 
    case "OldMercPal": return "/img/items/weapeon/all/OldMercPal.png" 
    case "OtherworldlyStory": return "/img/items/weapeon/all/OtherworldlyStory.png" 
    case "PocketGrimoire": return "/img/items/weapeon/all/PocketGrimoire.png" 
    case "Predator": return "/img/items/weapeon/all/Predator.png" 
    case "PrimordialJadeCutter": return "/img/items/weapeon/all/PrimordialJadeCutter.png" 
    case "PrimordialJadeWingedSpear": return "/img/items/weapeon/all/PrimordialJadeWingedSpear.png" 
    case "PrototypeAmber": return "/img/items/weapeon/all/PrototypeAmber.png" 
    case "PrototypeArchaic": return "/img/items/weapeon/all/PrototypeArchaic.png" 
    case "PrototypeCrescent": return "/img/items/weapeon/all/PrototypeCrescent.png" 
    case "PrototypeRancour": return "/img/items/weapeon/all/PrototypeRancour.png" 
    case "PrototypeStarglitter": return "/img/items/weapeon/all/PrototypeStarglitter.png" 
    case "Rainslasher": return "/img/items/weapeon/all/Rainslasher.png" 
    case "RavenBow": return "/img/items/weapeon/all/RavenBow.png" 
    case "RecurveBow": return "/img/items/weapeon/all/RecurveBow.png" 
    case "RoyalBow": return "/img/items/weapeon/all/RoyalBow.png" 
    case "RoyalGreatsword": return "/img/items/weapeon/all/RoyalGreatsword.png" 
    case "RoyalGrimoire": return "/img/items/weapeon/all/RoyalGrimoire.png" 
    case "RoyalLongsword": return "/img/items/weapeon/all/RoyalLongsword.png" 
    case "RoyalSpear": return "/img/items/weapeon/all/RoyalSpear.png" 
    case "Rust": return "/img/items/weapeon/all/Rust.png" 
    case "SacrificialBow": return "/img/items/weapeon/all/SacrificialBow.png" 
    case "SacrificialFragments": return "/img/items/weapeon/all/SacrificialFragments.png" 
    case "SacrificialGreatsword": return "/img/items/weapeon/all/SacrificialGreatsword.png" 
    case "SacrificialSword": return "/img/items/weapeon/all/SacrificialSword.png" 
    case "SeasonedHunterBow": return "/img/items/weapeon/all/SeasonedHunterBow.png" 
    case "SerpentSpine": return "/img/items/weapeon/all/SerpentSpine.png" 
    case "SharpshooterOath": return "/img/items/weapeon/all/SharpshooterOath.png" 
    case "SilverSword": return "/img/items/weapeon/all/SilverSword.png" 
    case "SkyriderGreatsword": return "/img/items/weapeon/all/SkyriderGreatsword.png" 
    case "SkyriderSword": return "/img/items/weapeon/all/SkyriderSword.png" 
    case "SkywardAtlas": return "/img/items/weapeon/all/SkywardAtlas.png" 
    case "SkywardBlade": return "/img/items/weapeon/all/SkywardBlade.png" 
    case "SkywardHarp": return "/img/items/weapeon/all/SkywardHarp.png" 
    case "SkywardPride": return "/img/items/weapeon/all/SkywardPride.png" 
    case "SkywardSpine": return "/img/items/weapeon/all/SkywardSpine.png" 
    case "Slingshot": return "/img/items/weapeon/all/Slingshot.png" 
    case "SnowTombedStarsilver": return "/img/items/weapeon/all/SnowTombedStarsilver.png" 
    case "SolarPearl": return "/img/items/weapeon/all/SolarPearl.png" 
    case "SongofBrokenPines": return "/img/items/weapeon/all/SongofBrokenPines.png" 
    case "StaffofHoma": return "/img/items/weapeon/all/StaffofHoma.png" 
    case "SummitShaper": return "/img/items/weapeon/all/SummitShaper.png" 
    case "SwordofDescension": return "/img/items/weapeon/all/SwordofDescension.png" 
    case "TheAlleyFlash": return "/img/items/weapeon/all/TheAlleyFlash.png" 
    case "TheBell": return "/img/items/weapeon/all/TheBell.png" 
    case "TheBlackSword": return "/img/items/weapeon/all/TheBlackSword.png" 
    case "TheCatch": return "/img/items/weapeon/all/TheCatch.png" 
    case "TheFlute": return "/img/items/weapeon/all/TheFlute.png" 
    case "TheStringless": return "/img/items/weapeon/all/TheStringless.png" 
    case "TheUnforged": return "/img/items/weapeon/all/TheUnforged.png" 
    case "TheViridescentHunt": return "/img/items/weapeon/all/TheViridescentHunt.png" 
    case "TheWidsith": return "/img/items/weapeon/all/TheWidsith.png" 
    case "ThrillingTalesofDragonSlayers": return "/img/items/weapeon/all/ThrillingTalesofDragonSlayers.png" 
    case "ThunderingPulse": return "/img/items/weapeon/all/ThunderingPulse.png" 
    case "TravelerHandySword": return "/img/items/weapeon/all/TravelerHandySword.png" 
    case "TwinNephrite": return "/img/items/weapeon/all/TwinNephrite.png" 
    case "VortexVanquisher": return "/img/items/weapeon/all/VortexVanquisher.png" 
    case "WasterGreatsword": return "/img/items/weapeon/all/WasterGreatsword.png" 
    case "Whiteblind": return "/img/items/weapeon/all/Whiteblind.png" 
    case "WhiteIronGreatsword": return "/img/items/weapeon/all/WhiteIronGreatsword.png" 
    case "WhiteTassel": return "/img/items/weapeon/all/WhiteTassel.png" 
    case "WindblumeOde": return "/img/items/weapeon/all/WindblumeOde.png" 
    case "WineandSong": return "/img/items/weapeon/all/WineandSong.png" 
    case "WolfGravestone": return "/img/items/weapeon/all/WolfGravestone.png" 
    
  }
}

function weapontimes(name){
  switch(name){
    case "AlleyHunter": return "wednesday" 
    case "AmenomaKageuchi": return "monday" 
    case "AmosBow": return "wednesday" 
    case "ApprenticeNotes": return "monday" 
    case "AquilaFavonia": return "monday" 
    case "BeginnerProtector": return "wednesday" 
    case "BlackcliffAgate": return "monday" 
    case "BlackcliffLongsword": return "monday" 
    case "BlackcliffPole": return "tuesday" 
    case "BlackcliffSlasher": return "tuesday" 
    case "BlackcliffWarbow": return "monday" 
    case "BlackTassel": return "wednesday" 
    case "BloodtaintedGreatsword": return "tuesday" 
    case "CompoundBow": return "wednesday" 
    case "CoolSteel": return "monday" 
    case "CrescentPike": return "monday" 
    case "DarkIronSword": return "monday" 
    case "Deathmatch": return "tuesday" 
    case "DebateClub": return "tuesday" 
    case "DodocoTales": return "tuesday" 
    case "DragonBane": return "tuesday" 
    case "DragonspineSpear": return "tuesday" 
    case "DullBlade": return "monday" 
    case "EbonyBow": return "wednesday" 
    case "ElegyfortheEnd": return "tuesday" 
    case "EmeraldOrb": return "monday" 
    case "EngulfingLightning": return "wednesday" 
    case "EverlastingMoonglow": return "monday" 
    case "EyeofPerception": return "tuesday" 
    case "FavoniusCodex": return "monday" 
    case "FavoniusGreatsword": return "wednesday" 
    case "FavoniusLance": return "wednesday" 
    case "FavoniusSword": return "monday" 
    case "FavoniusWarbow": return "wednesday" 
    case "FerrousShadow": return "monday" 
    case "FesteringDesire": return "wednesday" 
    case "FilletBlade": return "tuesday" 
    case "FreedomSworn": return "monday" 
    case "Frostbearer": return "wednesday" 
    case "HakushinRing": return "monday" 
    case "Halberd": return "tuesday" 
    case "Hamayumi": return "tuesday" 
    case "HarbingerofDawn": return "tuesday" 
    case "HunterBow": return "tuesday" 
    case "IronPoint": return "wednesday" 
    case "IronSting": return "wednesday" 
    case "KatsuragikiriNagamasa": return "tuesday" 
    case "KitainCrossSpear": return "wednesday" 
    case "LionRoar": return "monday" 
    case "LithicBlade": return "monday" 
    case "LithicSpear": return "wednesday" 
    case "LostPrayertotheSacredWinds": return "wednesday" 
    case "LuxuriousSeaLord": return "wednesday" 
    case "MagicGuide": return "monday" 
    case "MappaMare": return "wednesday" 
    case "MemoryofDust": return "wednesday" 
    case "Messenger": return "tuesday" 
    case "MistsplitterReforged": return "monday" 
    case "MitternachtsWaltz": return "monday" 
    case "OldMercPal": return "tuesday" 
    case "OtherworldlyStory": return "wednesday" 
    case "PocketGrimoire": return "monday" 
    case "Predator": return "tuesday" 
    case "PrimordialJadeCutter": return "tuesday" 
    case "PrimordialJadeWingedSpear": return "monday" 
    case "PrototypeAmber": return "tuesday" 
    case "PrototypeArchaic": return "wednesday" 
    case "PrototypeCrescent": return "tuesday" 
    case "PrototypeRancour": return "tuesday" 
    case "PrototypeStarglitter": return "wednesday" 
    case "Rainslasher": return "tuesday" 
    case "RavenBow": return "monday" 
    case "RecurveBow": return "wednesday" 
    case "RoyalBow": return "wednesday" 
    case "RoyalGreatsword": return "wednesday" 
    case "RoyalGrimoire": return "monday" 
    case "RoyalLongsword": return "monday" 
    case "RoyalSpear": return "tuesday" 
    case "Rust": return "monday" 
    case "SacrificialBow": return "tuesday" 
    case "SacrificialFragments": return "wednesday" 
    case "SacrificialGreatsword": return "tuesday" 
    case "SacrificialSword": return "wednesday" 
    case "SeasonedHunterBow": return "tuesday" 
    case "SerpentSpine": return "wednesday" 
    case "SharpshooterOath": return "tuesday" 
    case "SilverSword": return "monday" 
    case "SkyriderGreatsword": return "wednesday" 
    case "SkyriderSword": return "wednesday" 
    case "SkywardAtlas": return "tuesday" 
    case "SkywardBlade": return "tuesday" 
    case "SkywardHarp": return "tuesday" 
    case "SkywardPride": return "tuesday" 
    case "SkywardSpine": return "wednesday" 
    case "Slingshot": return "monday" 
    case "SnowTombedStarsilver": return "monday" 
    case "SolarPearl": return "monday" 
    case "SongofBrokenPines": return "monday" 
    case "StaffofHoma": return "wednesday" 
    case "SummitShaper": return "monday" 
    case "SwordofDescension": return "tuesday" 
    case "TheAlleyFlash": return "monday" 
    case "TheBell": return "monday" 
    case "TheBlackSword": return "tuesday" 
    case "TheCatch": return "wednesday" 
    case "TheFlute": return "tuesday" 
    case "TheStringless": return "monday" 
    case "TheUnforged": return "tuesday" 
    case "TheViridescentHunt": return "monday" 
    case "TheWidsith": return "tuesday" 
    case "ThrillingTalesofDragonSlayers": return "tuesday" 
    case "ThunderingPulse": return "tuesday" 
    case "TravelerHandySword": return "wednesday" 
    case "TwinNephrite": return "tuesday" 
    case "VortexVanquisher": return "wednesday" 
    case "WasterGreatsword": return "tuesday" 
    case "Whiteblind": return "monday" 
    case "WhiteIronGreatsword": return "wednesday" 
    case "WhiteTassel": return "monday" 
    case "WindblumeOde": return "wednesday" 
    case "WineandSong": return "tuesday" 
    case "WolfGravestone": return "wednesday" 
    
  }
}

function weaponimage(name){
  var imagefile = weaponimg(name)
  var days = weapontimes(name)
  document.cookie= name+"=2"
    var day = document.getElementById(days)
    var image = document.createElement("img")
    image.src = imagefile
    image.style.width="120px"
    image.style.margin="5px 0px 5px 0px"
    image.id=name+days
    image.onclick = function(){location.href = "/tools/weapon.html#"+days}
    image.classList.add("w3-hover-opacity")
    day.appendChild(image)
    var day = document.getElementById("sunday")
    var image = document.createElement("img")
    image.src = imagefile
    image.style.width="120px"
    image.style.margin="5px 0px 5px 0px"
    image.id=name+"sunday"
    image.onclick = function(){location.href = "/tools/weapon.html#"+days}
    image.classList.add("w3-hover-opacity")
    day.appendChild(image)
}


function removeweapon(name){
  var day = weapontimes(name)
  document.cookie= name+"=; expires=Thu, 01 Jan 1970 00:00:00 UTC"
  var days = document.getElementById(name+day)
  days.remove()
  var days = document.getElementById(name+"sunday")
  days.remove()
  
}
function weaponimagev(name,element){
  var imagefile = weaponimg(name)
  if(element == "") var day = document.getElementById("weapon")
  else var day = document.getElementById(element)
  var image = document.createElement("img")
  image.src = imagefile
  image.style.width="120px"
  image.style.margin="5px 0px 5px 0px"
  image.onclick = function(){location.href = "/tools/weapon.html#"+days}
  image.classList.add("w3-hover-opacity")
  day.appendChild(image)
}